# Provision masters and slave servers topology
---
- name: Provision a clustered master-slave topology messaging broker
  hosts: cluster
  vars:
    - amq_broker_start_server: false
  vars_files:
    - group_vars/variables.yml
  roles:
    - roles/ha-replication
