---
# Following variables (service_opts) are needed for dependent role ansible-service-creator.
amq_broker_instance_home: "{{ amq_broker_install_dest }}/{{ amq_broker_instance_dir }}"

service_opts:
  "artemis-{{ amq_broker_instance_dir }}":
    Description: "{% if 'artemis' in amq_broker_download_url|lower %}Apache ActiveMQ Artemis{% else %}Red Hat AMQ 7{% endif %}"
    After: "syslog.target network.target"
    Type: "simple"
    Environment: [
      "'JAVA_ARGS=\"--add-modules java.xml.bind\"'",
    ]
    PIDFile: "{{ amq_broker_instance_home }}/data/artemis.pid"
    ExecStart: "{{ amq_broker_instance_home }}/bin/artemis run"
#    ExecStop: "{{ amq_broker_instance_home }}/bin/artemis-service stop",
#    ExecReload: "{{ amq_broker_instance_home }}/bin/artemis-service restart",
    Restart: "no"
#    RestartSec: "10"
    User: "{{ amq_broker_user | default(amq_broker_default_user) }}"
    Group: "{{ amq_broker_user | default(amq_broker_default_user) }}"
    UMask: "0027"
    TimeoutStartSec: "3600"
    SuccessExitStatus: "143"
    WantedBy: "multi-user.target"
