---
# Common tasks for all brokers
- name: "Update discovery group name value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:discovery-groups/core_ns:discovery-group
    attribute: name
    value: "{{ amq_broker_cluster_discovery_group_name }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update discovery group address value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:discovery-groups/core_ns:discovery-group/core_ns:group-address
    value: "{{ amq_broker_cluster_broadcast_group_address }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update discovery group port value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:discovery-groups/core_ns:discovery-group/core_ns:group-port
    value: "{{ amq_broker_cluster_broadcast_group_port }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update broadcast group name value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:broadcast-groups/core_ns:broadcast-group
    attribute: name
    value: "{{ amq_broker_cluster_broadcast_group_name }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update broadcast group address value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:broadcast-groups/core_ns:broadcast-group/core_ns:group-address
    value: "{{ amq_broker_cluster_broadcast_group_address }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update broadcast  group port value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:broadcast-groups/core_ns:broadcast-group/core_ns:group-port
    value: "{{ amq_broker_cluster_broadcast_group_port }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update cluster name value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:cluster-connections/core_ns:cluster-connection
    attribute: name
    value: "{{ amq_broker_cluster_name }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"

- name: "Update discovery group ref value in {{ broker_xml }}"
  xml:
    file: "{{ broker_xml }}"
    xpath: /configuration_ns:configuration/core_ns:core/core_ns:cluster-connections/core_ns:cluster-connection/core_ns:discovery-group-ref
    attribute: discovery-group-name
    value: "{{ amq_broker_cluster_discovery_group_name }}"
    namespaces:
      configuration_ns: "{{ xml_configuration_ns }}"
      core_ns: "{{ xml_core_ns }}"